spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: "jdbc:h2:mem:dataround_link;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE"
    username: sa
    password: ""
  sql:
    init:
      schema-locations: classpath:h2-schema.sql
      mode: always