spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: "jdbc:h2:./data/dataround_link;AUTO_SERVER=TRUE;CASE_INSENSITIVE_IDENTIFIERS=true"
    username: sa
    password: ""
  sql:
    init:
      schema-locations: classpath:h2-schema.sql
      mode: always